### ISSUE TITLE
oi

### ISSUE THREAD

**Issue by el0xren** [AL-Noman21/Samsung-Floating-Features-Collection-#2]
my phone . bricked due . this, sir pls halp! ok "

**Comment by jhunrey7870** [comment]
Nice kang btw, anyway, unban @puerconiox009 on @FlameOSGroup else no Hvendor for ya

**Comment by bien2004official** [comment]
Even YumiProtection is 3000x better

**Comment by jhunrey7870** [comment]
Nah, Klaxosaur RC1 is way more better than AlNomanOS gay

**Comment by jhunrey7870** [comment]
Fix HWC wen?

**Comment by jhunrey7870** [comment]
Clang kernel wen

**Comment by el0xren** [comment]
eta wen

**Comment by jhunrey7870** [comment]
Sir i need stable OneUI 3.1 ROM, with fixed HWC, and powered by clang kernel, having AOD on j7xelte bro, with working stock camera bro, i need best rom bro, give bro, unban bro

**Comment by el0xren** [comment]
> Sir i need stable OneUI 3.1 ROM, with fixed HWC, and powered by clang kernel, having AOD on j7xelte bro, with working stock camera bro, i need best rom bro, give bro, unban bro

@AL-Noman21 wen eta

**Comment by FraSharp** [comment]
Hi . AL NOMAN 21 sir .

**Comment by jhunrey7870** [comment]
Nigga why delete comment
