### ISSUE TITLE
Marvel OS script issue

### ISSUE THREAD

**Issue by jhunrey7870** [AL-Noman21/Samsung-Floating-Features-Collection-#6]
Bro i flashed marvel a51 bro, no wifi bro, no IMEI baseband bro, help bro, pro development bro efs wipe bro by marvel os script bro unban bro bro bro @AL-Noman21

**Comment by el0xren** [comment]
> Bro i flashed marvel a51 bro, no wifi bro, no IMEI baseband bro, help bro, pro development bro efs wipe bro by marvel os script bro unban bro bro bro @AL-Noman21

yes bro please help!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ok "
